### ISSUE TITLE
ERROR: unrecognized parameter RNApeg.sh

### ISSUE THREAD

**Issue by GACGAMA** [stjude/RNApeg#18]
Hello everyone!
I'm trying to run RNApeg.sh after building it locally on my ArchLinux server.

When I use:

`docker run --mount  type=bind,source=/home/rnapeg/resultados/trueseq,target=/results 2022cd54d364 -b /home/Análises/Teste1/star/all_samples_ensembl_chimericwithinbam/99*.bam -f /home/references/cicero/reference/Homo_sapiens/GRCh38_no_alt/FASTA/GRCh38_no_alt.fa -r /home/references/cicero/reference/Homo_sapiens/GRCh38_no_alt/mRNA/RefSeq/refFlat.txt -O /home/Análises/Teste1/RNAPEG/trueseq/sample_5
`

OR

`docker run -v /home/Análises/Teste1/RNAPEG/trueseq:/results ghcr.io/stjude/rnapeg:latest RNApeg.sh -b /home/Análises/Teste1/star/all_samples_ensembl_chimericwithinbam/99*.bam -f /home/references/cicero/reference/Homo_sapiens/GRCh38_no_alt/FASTA/GRCh38_no_alt.fa -r /home/references/cicero/reference/Homo_sapiens/GRCh38_no_alt/mRNA/RefSeq/refFlat.txt`

OR

`singularity run --containall --bind /home/Análises/Teste1/RNAPEG/trueseq:/results docker://ghcr.io/stjude/rnapeg:latest RNApeg.sh -b /home/Análises/Teste1/star/all_samples_ensembl_chimericwithinbam/99*.bam -f /home/references/cicero/reference/Homo_sapiens/GRCh38_no_alt/FASTA/GRCh38_no_alt.fa -r /home/references/cicero/reference/Homo_sapiens/GRCh38_no_alt/mRNA/RefSeq/refFlat.txt`

I get:

`ERROR: unrecognized parameter RNApeg.sh

`
When I run the same, but without RNApeg.sh, I get:

`docker run --mount  type=bind,source=/home/rnapeg/resultados/trueseq,target=/results 2022cd54d364 -b /home/Análises/Teste1/star/all_samples_ensembl_chimericwithinbam/99*.bam -f /home/references/cicero/reference/Homo_sapiens/GRCh38_no_alt/FASTA/GRCh38_no_alt.fa -r /home/references/cicero/reference/Homo_sapiens/GRCh38_no_alt/mRNA/RefSeq/refFlat.txt -O /`

OR

`singularity run --containall --bind /home/Análises/Teste1/RNAPEG/trueseq:/results docker://ghcr.io/stjude/rnapeg:latest -b /home/Análises/Teste1/star/all_samples_ensembl_chimericwithinbam/99*.bam -f /home/references/cicero/reference/Homo_sapiens/GRCh38_no_alt/FASTA/GRCh38_no_alt.fa -r /home/references/cicero/reference/Homo_sapiens/GRCh38_no_alt/mRNA/RefSeq/refFlat.txt`

OR

`docker run -v /home/Análises/Teste1/RNAPEG/trueseq:/results ghcr.io/stjude/rnapeg:latest  -b /home/Análises/Teste1/star/all_samples_ensembl_chimericwithinbam/99*.bam -f /home/references/cicero/reference/Homo_sapiens/GRCh38_no_alt/FASTA/GRCh38_no_alt.fa -r /home/references/cicero/reference/Homo_sapiens/GRCh38_no_alt/mRNA/RefSeq/refFlat.txt`

I get:

`
ERROR: Bamfile '/home/Análises/Teste1/star/all_samples_ensembl_chimericwithinbam/99_FRAS202421989-1a_1.fqAligned.sortedByCoord.out.bam' DNE`

What should I do?

**Comment by GACGAMA** [comment]
I tried on another linux machine with ubuntu 20 and singularity, which gives me the output:
There is no runscript defined for this container\n

**Comment by jordan-rash** [comment]
Hi @GACGAMA...you're close.  You're confusing the path from your computers file system with that of inside the docker container.  

1st) The initial runs that gave you `ERROR: unrecognized parameter RNApeg.sh` is expected as the entrypoint of that container IS the `RNApeg.sh` script.  So you can just start with the flag options, as you found out.

2nd) Docker has no ability to access your local file system (unless it is mounted).  The `/home/references/cicero/reference/**` does not exist inside the container, there this is being executed.  So, not being familiar with you're system, i would suspect that the command youre looking for should be something like 

```bash
cp -r /home/Análises/Teste1/star/all_samples_ensembl_chimericwithinbam /home/references/cicero/reference

docker run \
-v /home/Análises/Teste1/RNAPEG/trueseq:/results \
-v /home/references/cicero/reference:/data \
ghcr.io/stjude/rnapeg:latest \
-b /data/all_samples_ensembl_chimericwithinbam/99*.bam \
-f /data/Homo_sapiens/GRCh38_no_alt/FASTA/GRCh38_no_alt.fa \
-r /data/Homo_sapiens/GRCh38_no_alt/mRNA/RefSeq/refFlat.txt
```

With that, your results should be found in `/home/Análises/Teste1/RNAPEG/trueseq`

**Comment by jordan-rash** [comment]
And just as a follow on, this is how I run the container, and it allows me to reference everything relative to where I am on my host system

`docker run -v $(pwd):/data -it ghcr.io/stjude/rnapeg:latest -b /data/file.bam -r /data/refFlat.txt -f /data/GRCh38_no_alt.fa`

**Comment by GACGAMA** [comment]
Referencing :/data with my system did work! I'm getting other errors from different reference files, but this is another issue!
