### ISSUE TITLE
RNApeg docker with Nextflow

### ISSUE THREAD

**Issue by acerverat** [stjude/RNApeg#26]
Hi,
I am trying to integrate RNApeg into a Nextflow pipeline and I have been getting an error that I think is related to Nextflow not supporting executable containers. When running the RNApeg related process Nextflow attempts to run a bash command, but the RNApeg container expects only parameters to run inside the RNApeg.sh. Do you know if there is a work around for this? I can provide more details if needed. Thanks for your time.

**Comment by adthrasher** [comment]
Hi @acerverat,

Sorry, we missed this originally. After some investigation, Nextflow executes tasks in the container with `bash`. WDL operates similarly. I've just merged changes in #27 and released v2.7.6 which adds `bash` to the container image. This should enable you to use RNApeg in Nextflow workflows.

**Comment by acerverat** [comment]
Hi,
great news. I had worked around it but this will definitely be a cleaner
solution.
Thanks!
