### ISSUE TITLE
Building XML-LibXML-2.0208 fails in (host) Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by bioruffo** [stjude/RNApeg#28]
Building XML-LibXML-2.0208, required for Bio::Tools::CodonTable, fails in (host) Ubuntu 20.04 LTS:
```
Building and testing XML-LibXML-2.0208 ... ! Installing XML::LibXML failed. See /root/.cpanm/work/1685495744.1/build.log for details. Retry with --force to force install it.
FAIL
``` 

The /root/.cpanm/work/1685495744.1/build.log file shows:

_[...]_
```
#   Failed test 'exception thrown during parse'
#   at t/35huge_mode.t line 58.
#          got: ''
#     expected: anything else

#   Failed test 'exception refers to entity reference loop'
#   at t/35huge_mode.t line 60.
#                   ''
#     doesn't match '(?^si:entity.*loop)'
# Looks like you failed 2 tests of 5.
t/35huge_mode.t ....................................
Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/5 subtests
``` 
_[...]_

[Old post from 2013 referring an issue with the same tests failing](https://rt.cpan.org/Public/Bug/Display.html?id=88375)

The error message suggests to add --force to the respective line in the Dockerfile, the old post also suggests skipping the test, and indeed substituting the line with,  
`RUN cpanm --force --no-wget Bio::Tools::CodonTable`   
Allows to complete the image build, which seems to run fine.

**Comment by adthrasher** [comment]
Thanks @bioruffo for the report and the suggested fix. This has been incorporated into v2.7.7.
