### ISSUE TITLE
add "-ignore-incompatible" param to junction_extraction_wrapper.pl command line in Docker RNApeg.sh

### ISSUE THREAD

**Issue by mnedmonson** [stjude/RNApeg#29]
An external user (email below) reports a BAM compatibility issue with RNApeg.  Their instrument-generated BAM maps to a variant of hg19, which is a bit different from the GRCh37-lite that RNApeg uses.  With that said, hg19 and GRCh37-lite are compatible for the primary chromosome sequences (chr1-22, X, and Y, however not MT).  RNApeg verifies compatibility between the input BAM and by default dies with an error if all the sequences don't have the same lengths.  However there is an option "-ignore-incompatible" that in this situation will process compatible reference sequences and ignore any others, which is a good workaround as it rescues the vast majority of the alignment.  IMO this should be added to the default command line in the Docker wrapper (RNApeg.sh).

contact email:

From: Steven Shideler <[Steven.Shideler@albertaprecisionlabs.ca](mailto:Steven.Shideler@albertaprecisionlabs.ca)>
Date: Wednesday, May 24, 2023 at 3:14 PM
To: Tian, Liqing <[Liqing.Tian@STJUDE.ORG](mailto:Liqing.Tian@STJUDE.ORG)>
Subject: Re: Illumina produce bam

To the Team at St. Jude, 
 
Hi we are looking to use CICERO for our illumina IRPE assay analysis and our bam files are produced by the Illumina NextSeq 2000 instrument. 
 
I’m writing to inquire as your instructions mention that if we are using a bam input file that wasn’t produced by aligning to GRCh37-lite to contact you. 
 
Our bam files are produced by the DRAGEN server onboard the instrument using “hg19_no_alt_haps_no_decoys” as the reference. 
 
What modifications are necessary to CICERO as I’m currently having trouble generating the junctions file with RNApeg using this Illumina output bam file. 
 
Regards,
Steven Shideler, BSc., MSc., B.I.T. 
Bioinformatician, Molecular Pathology 
Alberta Precision Laboratories (APL)

**Comment by bioruffo** [comment]
If I remember correctly, the Cicero demo file `MV4_11_RNAseq_1.bam` also has some incompatibility with GRCh37-lite. I might be wrong, but I think I had to use STAR's `ctat_genome_lib_build_dir/ref_genome.fa` reference for it.
It's no problem though, the -f option you provide takes care of different genome builds by pointing to the right reference.
